### ISSUE TITLE
Use your custom domain

### ISSUE THREAD

**Issue by ssaberan** [dollarbeale/website_project#28]
First configure an apex domain. Instructions: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

Then configure an apex domain and the www subdomain variant. Instructions: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain-and-the-www-subdomain-variant

Lastly, modify your deploy script to deploy to your custom domain. Instructions: https://vitejs.dev/guide/static-deploy.html#github-pages

**Comment by dollarbeale** [comment]
> First configure an apex domain. Instructions: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain
> 
> Then configure an apex domain and the www subdomain variant. Instructions: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain-and-the-www-subdomain-variant
> 
> Lastly, modify your deploy script to deploy to your custom domain. Instructions: https://www.w3schools.com/howto/howto_js_filter_elements.asp

Thank you so much for linking the instructions! I was able to successfully use my custom domain name for my website! I just need to modify my deploy script now. I think you may have placed the wrong link for the deployment script instructions. Are you able to link me to the one you intended?

**Comment by ssaberan** [comment]
> Thank you so much for linking the instructions! I was able to successfully use my custom domain name for my website! I just need to modify my deploy script now. I think you may have placed the wrong link for the deployment script instructions. Are you able to link me to the one you intended?

Done

**Comment by ssaberan** [comment]
Why was this closed? I don't see a PR updating the deploy script.

Edit: It appears those updates were merged directly to `main`, so I missed those changes.
